### ISSUE TITLE
Remove Workaround: add manually user tendrl-user

### ISSUE THREAD

**Issue by fbalak** [usmqe/usmqe-setup#108]
Remove workaround from pull request https://github.com/Tendrl/usmqe-setup/pull/107
It adds manually user tendrl-user to all hosts.
It is a workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1456552#c5

**Comment by mbukatov** [comment]
Fixed by e69eb36384a519059f6e799966f9b0d20e2382da
