### ISSUE TITLE
Replace meaningless gluster-centos role with one for gluster server, gluster client and so on

### ISSUE THREAD

**Issue by mbukatov** [usmqe/usmqe-setup#125]
We have one role which installs gluster packages, but it would be better if we have multiple roles for:

* gluster server machine (aka storage node)
* gluster client machine (aka client)

Also note that the roles doesn't need anything else beyond installing packages and enabling services, the rest of configuration would be handled by gdeploy.

**Comment by mbukatov** [comment]
Depends on (work on this issue is blocked until the following pull request is merged): https://github.com/usmqe/usmqe-setup/pull/126

**Comment by dahorak** [comment]
Fixed by https://github.com/usmqe/usmqe-setup/pull/130
