### ISSUE TITLE
Gluster Client setup may not survive reboot

### ISSUE THREAD

**Issue by mbukatov** [usmqe/usmqe-setup#136]
When I reboot all machines (including Tendrl machine, GlusterFS servers and a client), it could happen that a client wouldn't be able to mount the the volume during boot, so that the volume is not mounted. 

Since Gdeploy creates a fstab entry, running just `mount /mnt/volume_usmqe_alpha_distrep_4x2/` would be enough.

There are multiple possibilities how to address this:

* add extra task to mount the volume after reboot (not sure if a good idea, as it would require to be able to list all volumes)
* have a playbook to do this mount on a client and run it via pytest fixture (so that a test which requires to work with data on a volume would be sure that the volume is mounted)

**Comment by mkudlej** [comment]
There is another option:
- mark all volume mounts as automount

I think that all volumes created by gdeploy for specific gluster configuration should be marked as automount. And all volumes created by gdeploy from fixtures should be handled by that fixture or related tests.

**Comment by dahorak** [comment]
@mkudlej from my point of view, *automount* is not good solution here... it will probably bring more issues than resolve and what I remember, debugging automount issues is nightmare...

**Comment by mbukatov** [comment]
@mkudlej Do you mean [autofs](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/nfs-autofs.html)? Like [this](http://blog.nixpanic.net/2014/04/configuring-autofs-for-glusterfs-35.html)? I would need to check how it works and what the implications are, but it's an interesting option.

**Comment by mbukatov** [comment]
Marking as won't fix, client needs to run `mount -a` before trying to access glusterfs mountpoints.
