### ISSUE TITLE
Remove Workaround: exclude grafana-4.6.* in tendrl_unit_test_setup.yml #168

### ISSUE THREAD

**Issue by dahorak** [usmqe/usmqe-setup#171]
This workaround (PR https://github.com/usmqe/usmqe-setup/pull/168) is for https://github.com/Tendrl/monitoring-integration/issues/319 and should be removed once the relevant issue will be fixed.

**Comment by mbukatov** [comment]
Could we remove the workaround based on https://github.com/Tendrl/monitoring-integration/issues/319#issuecomment-368391427 already?

**Comment by dahorak** [comment]
@mbukatov probably yes, I'll create PR for that.
