### ISSUE TITLE
remove firewall.tendrl.yml

### ISSUE THREAD

**Issue by mbukatov** [usmqe/usmqe-setup#192]
remove `firewall.tendrl.yml` playbook

**Comment by mbukatov** [comment]
@dahorak do we use `firewall.tendrl.yml` for something?

**Comment by dahorak** [comment]
@mbukatov It can be safely removed.

**Comment by mbukatov** [comment]
Done in 99414a3c988d07e793a0b4c3913cad8960ef804d
