### ISSUE TITLE
Create test setup playbook for FIPS mode

### ISSUE THREAD

**Issue by mbukatov** [usmqe/usmqe-setup#206]
We need playbooks for enabling ~and disabling~ FIPS mode on RHEL 7 machines, called something like `test_setup.fips.yml` ~and `test_teardown.fips.yml`~. If this procedure is complicated, we can maintain the common tasks via ansible role in `roles/fips`.

Note that:

 * it's a little tricky, as it requires regeneration of initramfs and reboot
 * ~for a reliable teardown, we will need to make a backup of original initramfs during setup~
 * before starting actual work, we may check that it's not already automated via eg. [ansible-rhel7-nist-800-171-cui-role](https://github.com/RedHatOfficial/ansible-rhel7-nist-800-171-cui-role)

## Details

Documentation: [Chapter 8. Federal Standards and Regulations](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/chap-federal_standards_and_regulations)

See also:

* [ How can I make RHEL 6 or RHEL 7 FIPS 140-2 compliant? ](https://access.redhat.com/solutions/137833)
* [How to disable FIPS mode in RHEL 6 or RHEL 7 ](https://access.redhat.com/solutions/2422061)

**Comment by mbukatov** [comment]
@dahorak Would this work as I propose? If you think it's a good idea, I would ask @ebondare to start working on this.

**Comment by dahorak** [comment]
@mbukatov I'm not sure, if I fully understood it, but do we need "teardown" script for this? It seems to me more like particular configuration for whole test suite - not something related to only one or few tests.
It seems to be quite big intervention to the system, so I would maybe propose to configure it as part of the installation process (after full yum update, before reboot and before installation of Gluster and Tendrl).
About using/creating separated qcow images with already enabled FIPS mode - this might be also an option - especially if such qcow image already exists (I don't think so) or if the setup will take unreasonably long time and we would like to configure FIPS mode for each installation.
Also do we wan't to support/test this also on CentOS?

**Comment by mbukatov** [comment]
Ok, let's drop the teardown part and stick with the playbook approach (over qcow templates) now.

About CentOS: I don't see any reason why this wouldn't work with CentOS as well (I just checked and the fips rpm packages are indeed available in CentOS repositories as well). So if we will have a reason to run this setup in CentOS CI, we should be able to.

**Comment by mbukatov** [comment]
@ebondare is going to create the test setup playbook, @dahorak will then try to integrate into CI setup
