### ISSUE TITLE
Remove Workaround: tendrl-node-agent should not be explicitly stopped and started again

### ISSUE THREAD

**Issue by mbukatov** [usmqe/usmqe-setup#58]
Remove workaround for issue described in https://github.com/Tendrl/api/issues/86#issuecomment-285063914 introduced in commit f45cb68ad1aa6f16f9f18ea035318ed9fd184aaa of pull request https://github.com/Tendrl/usmqe-setup/pull/57.

**Comment by dahorak** [comment]
Reopened, because the issue still exists and workaround is present https://github.com/Tendrl/usmqe-setup/pull/81

**Comment by ltrilety** [comment]
The related issue is https://github.com/Tendrl/api/issues/132 not https://github.com/Tendrl/api/issues/86

**Comment by mbukatov** [comment]
No longer valid, the code has been removed from usmqe-setup some time ago.
